### ISSUE TITLE
Delete/update `master` branch?

### ISSUE THREAD

**Issue by dhruvbansal** [buidl-bitcoin/buidl-python#120]
This repo uses the `main` branch but the `master` branch still exists.  This is confusing for those of us who reflexively pull from `master` and find an essentially empty repo.

Propose replacing the current `readme.md` in `master` with a note saying to use `main` OR just delete the `master` branch entirely?

**Comment by mflaxman** [comment]
Deleted with the following:
```$ git push origin --delete master```

Thanks!
