### ISSUE TITLE
Accidental Commit to Main

### ISSUE THREAD

**Issue by mflaxman** [buidl-bitcoin/buidl-python#37]
Oof, I just accidentally committed to main! I meant to create a PR branch for you to review @jimmysong:
https://github.com/buidl-bitcoin/buidl-python/commit/9581b0e5fd729ce61a86ed8e3ee5210c2e1a3fc8

I believe this is non-controversial, but am happy to revert this if you disagree.

This came up in #33, as I think the name `entropy` in the `secure_mnemonic` method signature was confusing. By clarifying it as `extra_entropy` it helps developers have a better sense of what it is/does. And if it's going to be optional, XOR-ing the epoch seems like a very minimal safety feature.

**Comment by jimmysong** [comment]
this is fine.
